bot:
  name: ${BOT_NAME}
  key: ${BOT_KEY}
  admin-channel: ${BOT_ADMIN_CHANNEL}
  sub-channel: ${SUB_CHANNEL}
  url-web: ${WEB_URL}

spring:
  application:
    name: whiskey-code-bot
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT:8080}
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${KEY_STORE:keystore.p12}
    key-store-password: ${KEY_STORE_PASSWORD:123}
    key-store-type: PKCS12
    key-alias: springboot